version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "are-we-there-yet"
          version_requirement: "1.1.5"
      - match:
          dependency_name: "console-control-strings"
          version_requirement: "1.1.0"
      - match:
          dependency_name: "delegates"
          version_requirement: "1.0.0"
      - match:
          dependency_name: "ansi-regex"
          version_requirement: "2.1.1"
      - match:
          dependency_name: "aproba"
          version_requirement: "1.2.0"
      - match:
          dependency_name: "balanced-match"
          version_requirement: "1.0.0"
      - match:
          dependency_name: "brace-expansion"
          version_requirement: "1.1.11"
      - match:
          dependency_name: "code-point-at"
          version_requirement: "1.1.0"
      - match:
          dependency_name: "concat-map"
          version_requirement: "0.0.1"
      - match:
          dependency_name: "core-util-is"
          version_requirement: "1.0.2"
      - match:
          dependency_name: "inherits"
          version_requirement: "2.0.3"
      - match:
          dependency_name: "ini"
          version_requirement: "1.3.5"
      - match:
          dependency_name: "is-fullwidth-code-point"
          version_requirement: "1.0.0"
      - match:
          dependency_name: "minimatch"
          version_requirement: "3.0.4"
      - match:
          dependency_name: "minimist"
          version_requirement: "0.0.8"
      - match:
          dependency_name: "minipass"
          version_requirement: "2.3.5"
      - match:
          dependency_name: "minizlib"
          version_requirement: "1.2.1"
      - match:
          dependency_name: "number-is-nan"
          version_requirement: "1.0.1"
      - match:
          dependency_name: "object-assign"
          version_requirement: "4.1.1"
      - match:
          dependency_name: "once"
          version_requirement: "1.4.0"
      - match:
          dependency_name: "safe-buffer"
          version_requirement: "5.1.2"
      - match:
          dependency_name: "string-width"
          version_requirement: "1.0.2"
      - match:
          dependency_name: "strip-ansi"
          version_requirement: "3.0.1"
      - match:
          dependency_name: "wrappy"
          version_requirement: "1.0.2"
      - match:
          dependency_name: "yallist"
          version_requirement: "3.0.3"
      - match:
          dependency_name: "fstream"
          version_requirement: "1.0.11"
      - match:
          dependency_name: "gauge"
          version_requirement: "2.7.4"
      - match:
          dependency_name: "get-stdin"
          version_requirement: "4.0.1"
      - match:
          dependency_name: "has-unicode"
          version_requirement: "2.0.1"
      - match:
          dependency_name: "https-proxy-agent"
          version_requirement: "2.2.1"
      - match:
          dependency_name: "ms"
          version_requirement: "2.1.1"
      - match:
          dependency_name: "is-utf8"
          version_requirement: "0.2.1"
      - match:
          dependency_name: "load-json-file"
          version_requirement: "1.1.0"
      - match:
          dependency_name: "map-obj"
          version_requirement: "1.0.1"
      - match:
          dependency_name: "npmlog"
          version_requirement: "4.1.2"
      - match:
          dependency_name: "read-pkg"
          version_requirement: "1.1.0"
      - match:
          dependency_name: "path-type"
          version_requirement: "1.1.0"
      - match:
          dependency_name: "pify"
          version_requirement: "2.3.0"
      - match:
          dependency_name: "read-pkg-up"
          version_requirement: "1.0.1"
      - match:
          dependency_name: "find-up"
          version_requirement: "1.1.2"
      - match:
          dependency_name: "path-exists"
          version_requirement: "2.1.0"
      - match:
          dependency_name: "strip-bom"
          version_requirement: "2.0.0"
      - match:
          dependency_name: "wide-align"
          version_requirement: "1.1.3"
      - match:
          dependency_name: "mkdirp"
          version_requirement: "0.5.1"
      - match:
          dependency_name: "js-yaml"
          version_requirement: "3.12.0"
      - match:
          dependency_name: "acorn"
          version_requirement: "6.1.1"
      - match:
          dependency_name: "websocket-extensions"
          version_requirement: "0.1.3"
      - match:
          dependency_name: "npm-registry-fetch"
          version_requirement: "4.0.4"
