spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: newClient
            client-secret: newClientSecret
            scope: read,write
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/new-client/login/oauth2/code/custom
        provider:
          custom:
            authorization-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/auth
            token-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/token
            user-info-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
  thymeleaf:
    cache: false
    
server: 
  port: 8082
  servlet: 
    context-path: /jwt-client
    
logging: 
  level: 
    org.springframework: INFO
        